---
title: Jumaidil Awal
timezone: Asia/Jakarta
collections:
  blog_categories:
    title: Categories
    output: true
  portfolios:
    title: Portfolios
    output: true
  posts:
    title: Posts
    output: true
  blog_tags:
    title: Tags
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: portfolios
  values:
    layout: portfolio
    permalink: "/porto/:title"
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
    excerpt: 
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: blog_tags
  values:
    slug: 
    layout: tag
    permalink: "/tag/:slug/"
- scope:
    path: ''
    type: blog_categories
  values:
    slug: 
    layout: category
    permalink: "/category/:slug/"
description: Jumaidil Awal
permalink: pretty
plugins:
- jekyll-remote-theme
- jekyll-favicon
remote_theme: pages-themes/cayman@v0.2.0
author:
  name: Jumaidil Awal
  photo: "/uploads/best-profile-photo-ever.png"
  twitter: pak_aidil
  instagram: pak.aidil
  facebook: jumaidil.awal
  github: ideal1st
favicon:
  source: "/uploads/best-profile-photo-small.png"
copyright:
  notice: Jumaidil Awal Â© 2022
  disclaimer: 'Theme modified from: Cayman by @parkr'
